//
// $Id: Linux_LocalFileSystemMetric.mof,v 1.3 2004/08/04 11:27:36 mihajlov Exp $
//
// (C) Copyright IBM Corp. 2003, 2004
//
// THIS FILE IS PROVIDED UNDER THE TERMS OF THE COMMON PUBLIC LICENSE
// ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
// CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
//
// You can obtain a current copy of the Common Public License from
// http://oss.software.ibm.com/developerworks/opensource/license-cpl.html
//
// Author:       Heidi Neumann <heidineu@de.ibm.com>
// Contributors: 
//
// Description:
// This mof file contains the definitions for the Local File System 
// Metrics, provided by the shared library libmetricLocalFileSystem.so
//



// ===================================================================
// Linux_LocalFileSystemMetric
// ===================================================================

[ Provider("cmpi:OSBase_MetricDefinitionProvider"),
  Description ("Class for Local File System Metric Definitions")
]
class Linux_LocalFileSystemMetric : CIM_BaseMetricDefinition
{ };


// ===================================================================
// Linux_LocalFileSystemMetricValue
// ===================================================================

[ Provider("cmpi:OSBase_MetricValueProvider"),
  Description ("Class for Local File System Metric Value")
]
class Linux_LocalFileSystemMetricValue : CIM_BaseMetricValue
{ };


// ===================================================================
// instance definitions
// ===================================================================

instance of Linux_MetricPlugin  
{
	MetricDefinitionClassName = "Linux_LocalFileSystemMetric";
 	MetricPluginName = "libmetricLocalFileSystem.so";
};

instance of Linux_RepositoryPlugin  
{
	MetricDefinitionClassName = "Linux_LocalFileSystemMetric";
 	RepositoryPluginName = "librepositoryLocalFileSystem.so";
};


instance of Linux_MetricValueDefinition
{
	MetricValueClassName = "Linux_LocalFileSystemMetricValue";
	MetricDefinitionClassName = "Linux_LocalFileSystemMetric";
};
