//
// $Id: Linux_NetworkPortMetric.mof,v 1.3 2004/10/07 06:22:01 mihajlov Exp $
//
// (C) Copyright IBM Corp. 2003, 2004
//
// THIS FILE IS PROVIDED UNDER THE TERMS OF THE COMMON PUBLIC LICENSE
// ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
// CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
//
// You can obtain a current copy of the Common Public License from
// http://oss.software.ibm.com/developerworks/opensource/license-cpl.html
//
// Author:       Heidi Neumann <heidineu@de.ibm.com>
// Contributors: 
//
// Description:
// This mof file contains the definitions for the Network Port
// Metrics, provided by the shared library libmetricNetworkPort.so
//



// ===================================================================
// Linux_NetworkPortMetric
// ===================================================================

[ Provider("cmpi:OSBase_MetricDefinitionProvider"),
  Description ("Class for Local File System Metric Definitions")
]
class Linux_NetworkPortMetric : CIM_BaseMetricDefinition
{ };


// ===================================================================
// Linux_NetworkPortMetricValue
// ===================================================================

[ Provider("cmpi:OSBase_MetricValueProvider"),
  Description ("Class for Local File System Metric Value")
]
class Linux_NetworkPortMetricValue : CIM_BaseMetricValue
{ };


// ===================================================================
// instance definitions
// ===================================================================

instance of Linux_MetricPlugin  
{
	MetricDefinitionClassName = "Linux_NetworkPortMetric";
 	MetricPluginName = "libmetricNetworkPort.so";
};

instance of Linux_RepositoryPlugin  
{
	MetricDefinitionClassName = "Linux_NetworkPortMetric";
 	RepositoryPluginName = "librepositoryNetworkPort.so";
 	CIMTranslationPluginName = "libcimplugNetworkPort.so";
};


instance of Linux_MetricValueDefinition
{
	MetricValueClassName = "Linux_NetworkPortMetricValue";
	MetricDefinitionClassName = "Linux_NetworkPortMetric";
};
