# Makefile for SBLIM Base Instrumentation 


include ../../rules

.PHONY: all install uninstall clean distclean

all:

install: 
	$(MAKE) -f makefile.pegasus install
	$(MAKE) -f makefile.OperatingSystem.pegasus install
	$(MAKE) -f makefile.UnixProcess.pegasus install
	$(MAKE) -f makefile.Processor.pegasus install
	$(MAKE) -f makefile.LocalFileSystem.pegasus install
	$(MAKE) -f makefile.NetworkPort.pegasus install

uninstall:

clean:

distclean:










