//
// $Id: SampleRegistration.mof,v 1.1 2003/10/17 13:56:01 mihajlov Exp $
//
// (C) Copyright IBM Corp. 2003
//
// THIS FILE IS PROVIDED UNDER THE TERMS OF THE COMMON PUBLIC LICENSE
// ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
// CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
//
// You can obtain a current copy of the Common Public License from
// http://oss.software.ibm.com/developerworks/opensource/license-cpl.html
//
// Author:       Viktor Mihajlovski
// Contributors:
//
// Description:
// Sample Metric Registration Classes
//

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_MetricDefinitionProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "OSBase_MetricDefinitionProvider";
   CapabilityID = "2";
   //Name of the CIM class as defined in the mof
   ClassName = "Linux_Sample3";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2 }; // Instance
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_MetricDefinitionProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "OSBase_MetricDefinitionProvider";
   CapabilityID = "3";
   //Name of the CIM class as defined in the mof
   ClassName = "Linux_Sample4";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2 }; // Instance
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_MetricValueProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "OSBase_MetricValueProvider";
   CapabilityID = "2";
   //Name of the CIM class as defined in the mof
   ClassName = "Linux_Sample3Value";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2 }; // Instance
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "OSBase_MetricValueProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "OSBase_MetricValueProvider";
   CapabilityID = "3";
   //Name of the CIM class as defined in the mof
   ClassName = "Linux_Sample4Value";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2 }; // Instance
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};
