//
// $Id: Sample.mof,v 1.2 2009/05/20 19:39:56 tyreld Exp $
//
// (C) Copyright IBM Corp. 2003, 2009
//
// THIS FILE IS PROVIDED UNDER THE TERMS OF THE ECLIPSE PUBLIC LICENSE
// ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
// CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
//
// You can obtain a current copy of the Eclipse Public License from
// http://www.opensource.org/licenses/eclipse-1.0.php
//
// Author:       Viktor Mihajlovski
// Contributors:
//
// Description:
// Sample CIM classes for Metrics
//

[ Provider("cmpi:OSBase_MetricDefinitionProvider"),
  Description ("Class for Sample Metric Definitions")
]
class Linux_Sample3 : CIM_BaseMetricDefinition
{ };

instance of Linux_MetricPlugin  
{
	MetricDefinitionClassName = "Linux_Sample3";
 	MetricPluginName = "libmetricSample3.so";
};

[ Provider("cmpi:OSBase_MetricDefinitionProvider"),
  Description ("Another Class for Sample Metric Definitions")
]
class Linux_Sample4 : CIM_BaseMetricDefinition
{ };

instance of Linux_MetricPlugin  
{
	MetricDefinitionClassName = "Linux_Sample4";
 	MetricPluginName = "libmetricSample4.so";
};


[ Provider("cmpi:OSBase_MetricValueProvider"),
  Description ("Class for Sample Metric Value")
]
class Linux_Sample3Value : CIM_BaseMetricValue
{ };


instance of Linux_MetricValueDefinition
{
	MetricValueClassName = "Linux_Sample3Value";
	MetricDefinitionClassName = "Linux_Sample3";
};

[ Provider("cmpi:OSBase_MetricValueProvider"),
  Description ("Class for Sample Metric Value")
]
class Linux_Sample4Value : CIM_BaseMetricValue
{ };


instance of Linux_MetricValueDefinition
{
	MetricValueClassName = "Linux_Sample4Value";
	MetricDefinitionClassName = "Linux_Sample4";
};
